/**
 * VerilogEmitter.js
 *
 * Translates a GateLab circuit snapshot (nodes + wires) into a synthesizable
 * structural Verilog netlist. "Structural" is the operative word here — this
 * does NOT compile down to behavioral `assign x = a & b` statements. It
 * instantiates Verilog's built-in primitive gates (and/or/not/nand/nor/xor/
 * xnor) one-for-one against the gates on the canvas, wired exactly as drawn.
 *
 * Why structural instead of behavioral:
 *   Behavioral Verilog (`assign`) has no concept of a feedback loop — an
 *   `assign` statement that reads a signal it also drives is either a
 *   combinational loop error or requires manual `always @*` restructuring.
 *   But half of Unit III is built from *exactly that* — cross-coupled NAND/
 *   NOR latches feeding back into their own inputs, which is precisely how
 *   real SR latches and flip-flops are built at the transistor/gate level.
 *   Structural primitive instantiation supports feedback natively, because
 *   that's how real hardware nets work — no cycle detection, no rewriting,
 *   no special-casing flip-flops vs combinational gates. The netlist is
 *   just... the circuit, the same way GraphEvaluator treats it. One model,
 *   two representations.
 *
 * Signal-state parity with the simulator:
 *   An unconnected gate input (or an input fed by a wire with `broken:
 *   true`) renders as a dashed grey "undefined" wire in WireLayer and
 *   evaluates to `undefined` in GraphEvaluator. This emitter mirrors that
 *   exactly by tying such inputs to 1'bx (Verilog's "unknown" logic value)
 *   rather than defaulting them to 0 — so a circuit that's visibly
 *   incomplete on the canvas is *also* visibly incomplete (X-propagating)
 *   in simulation, instead of silently and incorrectly "working."
 *
 * This module has zero React / Konva / Zustand dependencies — same
 * philosophy as GraphEvaluator.js. Pure function in, string out.
 */

const GATE_PRIMITIVES = {
  AND:  'and',
  OR:   'or',
  NOT:  'not',
  NAND: 'nand',
  NOR:  'nor',
  XOR:  'xor',
  XNOR: 'xnor',
}

// NOT is the only single-input primitive; everything else is >=2 and the
// primitive itself accepts arbitrary arity, which is what lets a 3-input
// NAND (used in master-slave JK flip-flops) emit correctly without special
// casing — same reasoning GraphEvaluator uses for getInputCount().
const STRUCTURAL_MIN_INPUTS = { NOT: 1 }

/**
 * Verilog identifiers can't start with a digit and can't collide with
 * reserved words. GateLab node ids are author-chosen (short slugs like
 * 'x1a', 'd1', 'vcc0') and were never designed against Verilog's keyword
 * list, so instead of validating each one, every emitted net/instance name
 * gets an unconditional 'n_' / 'g_' prefix. That fully sidesteps the
 * problem regardless of what the source lesson happens to call things.
 */
function sanitize(id) {
  return String(id).replace(/[^a-zA-Z0-9_]/g, '_')
}
function netName(nodeId) { return `n_${sanitize(nodeId)}` }
function instName(nodeId) { return `g_${sanitize(nodeId)}` }

/**
 * emitVerilog(nodes, wires, options?)
 *
 * @param {object[]} nodes         - same shape as GraphEvaluator's nodes
 * @param {object[]} wires         - same shape as GraphEvaluator's wires
 * @param {object}   [options]
 * @param {string}   [options.moduleName]  - defaults to 'gatelab_circuit'
 * @param {string}   [options.lessonTitle] - optional header comment context
 * @param {string}   [options.workOrder]   - optional header comment context
 * @returns {{code: string, warnings: string[]}}
 */
export function emitVerilog(nodes, wires, options = {}) {
  const moduleName = sanitize(options.moduleName || 'gatelab_circuit')

  // ── wiresByDest[nodeId][inputIndex] = fromNodeId ──────────────────────
  // Deliberately mirrors GraphEvaluator's construction: broken wires are
  // excluded here exactly as they're excluded from evaluation, so a wire
  // you've flagged broken in a fault-injection lesson is floating in the
  // export too, not silently still-connected.
  const wiresByDest = {}
  for (const node of nodes) wiresByDest[node.id] = {}
  for (const wire of wires) {
    if (wire.broken) continue
    const { nodeId, index = 0 } = wire.to
    wiresByDest[nodeId][index] = wire.from.nodeId
  }

  const inputNodes  = nodes.filter(n => n.type === 'INPUT' || n.type === 'CLOCK')
  const outputNodes = nodes.filter(n => n.type === 'OUTPUT')
  const constNodes  = nodes.filter(n => n.type === 'CONST')
  const gateNodes   = nodes.filter(n => n.type in GATE_PRIMITIVES)

  const warnings = []

  // ── Port list ───────────────────────────────────────────────────────
  const ports = [
    ...inputNodes.map(n => netName(n.id)),
    ...outputNodes.map(n => netName(n.id)),
  ]

  const lines = []
  lines.push(`// ${'-'.repeat(70)}`)
  lines.push(`// Auto-generated by GateLab — Verilog export`)
  if (options.workOrder)   lines.push(`// Work order : ${options.workOrder}`)
  if (options.lessonTitle) lines.push(`// Lesson     : ${options.lessonTitle}`)
  lines.push(`// Generated  : ${new Date().toISOString()}`)
  lines.push(`//`)
  lines.push(`// This is a STRUCTURAL netlist — every instance below is a`)
  lines.push(`// Verilog built-in primitive gate, wired exactly as drawn on`)
  lines.push(`// the GateLab canvas. Feedback loops (latches, flip-flops)`)
  lines.push(`// are preserved as real structural feedback, not rewritten.`)
  lines.push(`//`)
  lines.push(`// 1'bx below means that input was unwired (or its wire was`)
  lines.push(`// flagged broken) at export time — matches the dashed grey`)
  lines.push(`// "undefined" wire state you'd see on the canvas.`)
  lines.push(`// ${'-'.repeat(70)}`)
  lines.push('')
  lines.push(`module ${moduleName} (`)
  lines.push(ports.map(p => `    ${p}`).join(',\n') || '    /* no ports */')
  lines.push(');')
  lines.push('')

  // ── Port direction declarations ────────────────────────────────────
  if (inputNodes.length) {
    lines.push('  // Inputs')
    for (const n of inputNodes) {
      const tag = n.type === 'CLOCK' ? '  // clock input' : ''
      lines.push(`  input ${netName(n.id)};${tag}`)
    }
    lines.push('')
  }
  if (outputNodes.length) {
    lines.push('  // Outputs')
    for (const n of outputNodes) lines.push(`  output ${netName(n.id)};`)
    lines.push('')
  }

  // ── Constants ───────────────────────────────────────────────────────
  if (constNodes.length) {
    lines.push('  // Tied constants')
    for (const n of constNodes) {
      lines.push(`  wire ${netName(n.id)} = 1'b${n.value ? '1' : '0'};`)
    }
    lines.push('')
  }

  // ── Internal nets (every gate's output needs a named wire) ────────
  if (gateNodes.length) {
    lines.push('  // Internal nets')
    lines.push(`  wire ${gateNodes.map(n => netName(n.id)).join(', ')};`)
    lines.push('')
  }

  // ── Helper: resolve one input pin to a net name, tracking warnings ──
  function resolveInput(node, index) {
    const fromId = wiresByDest[node.id]?.[index]
    if (fromId == null) {
      warnings.push(`${node.type} '${node.id}' input[${index}] is unwired — tied to 1'bx`)
      return "1'bx"
    }
    return netName(fromId)
  }

  // ── Gate instantiations ────────────────────────────────────────────
  if (gateNodes.length) {
    lines.push('  // Gates')
    for (const node of gateNodes) {
      const prim = GATE_PRIMITIVES[node.type]
      const structuralMin = STRUCTURAL_MIN_INPUTS[node.type] ?? 2
      const wiredIndices = Object.keys(wiresByDest[node.id] || {}).map(Number)
      const maxWiredIndex = wiredIndices.length ? Math.max(...wiredIndices) : -1
      const inputCount = Math.max(structuralMin, maxWiredIndex + 1)

      const inputNets = []
      for (let i = 0; i < inputCount; i++) inputNets.push(resolveInput(node, i))

      const args = [netName(node.id), ...inputNets].join(', ')
      lines.push(`  ${prim} ${instName(node.id)} (${args});`)
    }
    lines.push('')
  }

  // ── Output assigns (an OUTPUT node just reflects its one input net) ─
  if (outputNodes.length) {
    lines.push('  // Output taps')
    for (const node of outputNodes) {
      const fromId = wiresByDest[node.id]?.[0]
      if (fromId == null) {
        warnings.push(`OUTPUT '${node.id}' is unwired — tied to 1'bx`)
        lines.push(`  assign ${netName(node.id)} = 1'bx; // unwired`)
      } else {
        lines.push(`  assign ${netName(node.id)} = ${netName(fromId)};`)
      }
    }
    lines.push('')
  }

  lines.push('endmodule')
  lines.push('')

  if (warnings.length) {
    lines.push('/* ' + '-'.repeat(68))
    lines.push(' * Export warnings — the circuit was incomplete at export time:')
    for (const w of warnings) lines.push(` *   - ${w}`)
    lines.push(' ' + '-'.repeat(69) + '*/')
  }

  return { code: lines.join('\n'), warnings }
}
